version: '3.9'

services:
  web:
    build: .
    command: sh -c "/wait-for-it.sh db 5432 flask run --host=0.0.0.0"
    container_name: norktown_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: norktown_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: norktown_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build: .
    command: sh -c "/wait-for-it.sh db 5432 pytest --cov=app app/tests"
    container_name: norktown_test
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: norktown_db

volumes:
  postgres_data:
